### PR TITLE
Update key size and signature algorithm.

### LINKED ISSUE #851: gcf-test.py fails on CentOS 7
Following the instructions in README-gcf.txt on CentOS 7 results in an SSL error:

    ssl.SSLError: [Errno 1] _ssl.c:504: error:1409441B:SSL routines:SSL3_READ_BYTES:tlsv1 alert decrypt error

The full stack output of the command is:
```
$ src/gcf-test.py 
INFO:gcf-test:CH Server is https://127.0.0.1:8000/. Using keyfile /home/tmitchel/.gcf/alice-key.pem, certfile /home/tmitchel/.gcf/alice-cert.pem
INFO:gcf-test:AM Server is https://127.0.0.1:8001/. Using keyfile /home/tmitchel/.gcf/alice-key.pem, certfile /home/tmitchel/.gcf/alice-cert.pem
Traceback (most recent call last):
  File "src/gcf-test.py", line 562, in <module>
    sys.exit(main())
  File "src/gcf-test.py", line 557, in main
    exercise_am(ch_server, am_server, opts.api_version)
  File "src/gcf-test.py", line 426, in exercise_am
    slice_cred_string = ch_server.CreateSlice()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/home/tmitchel/geni-tools/src/gcf/omnilib/xmlrpc/client.py", line 125, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, ssl_version=self.ssl_version, ciphers=self.ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 387, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:504: error:1409441B:SSL routines:SSL3_READ_BYTES:tlsv1 alert decrypt error
```

### PR DESCRIPTION
**Pull request by tcmitchell**
Change default key size from 1024 to 2048. Change default signature
algorithm from md5 to sha256. CentOS 7 refuses SSL connections when
the server uses a certificate with an md5 signature
algorithm. Updating to sha256 fixes the issue. While we're there,
update to larger keys as well since 1024 is on the way out.

Fixes #851. Fix tested on CentOS 7, CentOS 6, Ubuntu 14.04, Ubuntu 12.04.

### CODE REVIEW

**Comment by ahelsing** [comment]
Works on Ubu10.04

**Comment by ahelsing** [comment]
works on Windows7

**Comment by ahelsing** [comment]
works on OS X
