### ISSUE TITLE
Consider restricting SSL versions in Omni

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#745]
See ticket #744

Due to POODLE vulnerability, we'd ideally avoid using SSLv3.

Unfortunately:
Our client.py uses xmlrpclib.safeconnection.makeconnection

xmlrpclib creates the HTTPS directly

httplib.httpsconnection is where we call wrap_socket - using the defaults for SSL version and ciphers

The default ciphers in my 2.7 version of python in ssl.py:
`DEFAULT:aNULL:eNULL:LOW:EXPORT:SSLv2`

So as far as I can tell, we would need to over-ride httpsconnection and xmlrpclib.safetransport

 _Imported from trac ticket [#745](http://trac.gpolab.bbn.com/gcf/ticket/745),  created by ahelsing on 10-16-2014 at 11:29, last modified: 05-15-2015 at 08:56_

**Comment by ahelsing** [comment]
Ran into something related today.

Symptom: Users of the Mac Stitcher binary see in the logs:
`SCS gave error: [Errno 54] Connection reset by peer`

This does not impact users on Linux or Windows, to my knowledge.

The issue appears to be that the I2 SCS is now returning SSL Error# 54 from Mac clients. These are I think running OpenSSL 0.9.8zd.
If you run "openssl version" on your Mac, you can confirm.

My Linux box is running openssl 1.0.1 - and it works fine

From my testing, it appears that the I2 SCS only accepts TLS1 connections - not SSL2 or SSL3 connections. At least, not usually. But unfortunately OpenSSL on the Mac defaults to using SSLv2 initially, which fails with that error #54.

=====

My testing details:

On my Mac, with `openssl 0.9.8zd`:

TLS1 works:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -key mykey.key -cert mycert.pem -tls1
>>> TLS 1.0 Handshake [length 005f], ClientHello
    Protocol  : TLSv1
    Cipher    : AES256-SHA
```
Forcing openssl s_client to send SNI information (which appears to change the protocol) also works:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443  -servername geni-scs.net.internet2.edu  -key mykey.key -cert mycert.pem
>>> TLS 1.0 Handshake [length 0082], ClientHello

    Protocol  : TLSv1
    Cipher    : AES256-SHA
```

Forcing it to not use SSLv2 works:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443  -key mykey.key -cert mycert.pem -no_ssl2
>>> TLS 1.0 Handshake [length 005f], ClientHello
    Protocol  : TLSv1
    Cipher    : AES256-SHA
```

But these fail:

Force use SSLv2 fails with Errno 54:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -ssl2  -key mykey.key -cert mycert.pem
CONNECTED(00000003)
write:errno=54
```
Force use SSLV3 but without SNI fails with a different error:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -ssl3  -key mykey.key -cert mycert.pem
CONNECTED(00000003)
66458:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.20.2/src/ssl/s3_pkt.c:1145:SSL alert number 40
66458:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.20.2/src/ssl/s3_pkt.c:566:
```
That's a generic SSL handshake error, that I believe means that they've disabled SSLv3 support, which was recommended for the POODLE bug.

----

Comparing to results on my Ubuntu 14.04 box:
`OpenSSL 1.0.1f`

Default connection attempt:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem
>>> TLS 1.2 Handshake [length 012c], ClientHello
    Protocol  : TLSv1
    Cipher    : AES256-SHA
```

Force use ssl2: not a valid option
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem -ssl2
```

Force use ssl3:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem -ssl3
>>> SSL 3.0 Handshake [length 0085], ClientHello
3073787580:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:s3_pkt.c:1262:SSL alert number 40
```

Force use ssl3 with -servername: Same as for force use ssl3
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem -ssl -servername geni-scs.net.internet2.edu
```

Force use tls1:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem -tls1
>>> TLS 1.0 Handshake [length 00d0], ClientHello
    Protocol  : TLSv1
    Cipher    : AES256-SHA
```

Force use TLS1_1: or TLS1_2:
```
$ openssl s_client -connect geni-scs.net.internet2.edu:8443 -msg -state   -key mykey.key -cert mycert.pem -tls1_1 (or -tls1_2)
>>> TLS 1.1 Handshake [length 00d0], ClientHello (or 1.2)
>>> TLS 1.0 Alert [length 0002], fatal protocol_version
    02 46
SSL3 alert write:fatal:protocol version
SSL_connect:error in SSLv3 read server hello A
3074160316:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:339:
```

**Comment by ahelsing** [comment]
A package on top of pyOpenSSL and pyasn1 modules that supports sending the server_hostname: https://code.google.com/p/ssl-sni/

Some client code for doing TLS1 and sending the SNI information from python: https://github.com/msabramo/pyOpenSSL/blob/master/examples/sni/client.py

A nice github issue against the requests library pointing the finger at SNI support:
https://github.com/kennethreitz/requests/issues/2022
That thread also says:
`crappy OpenSSL that OS X ships with by default. Version 0.9.8y has some real problems with performing SSL handshakes, and some servers don't tolerate it well.`

**Comment by ahelsing** [comment]
Could I over-ride our python code to force starting with TLS1?

ssl.py def wrap_socket(.....ssl_version=PROTOCOL_SSLv23). We may want PROTOCOL_TLSv1.

xmlrpclib.py class SafeTransport def make_connection set self._connection = host, HTTPS(chost, None, **(x509 or {})) and returns self._connection[1]

httplib.py class HTTPS sets _connection_class = HTTPSConnection so that __init_ does _setup with an instance of HTTPSConnection

httplib.py class HTTPSConnection def connect does self.sock = ssl.wrap_socket.....

So I'd need to redefine the connect method on HTTPSConnection or reset the self.sock in the connection.
Could I redefine ssl.PROTOCOL_SSLv23 = ssl.PROTOCOL_TLSv1 ?

**Comment by ahelsing** [comment]
Luisa reports that stitcher fails talking to the SCS for her on these systems:

 - "OpenSSL 1.0.1c 10 May 2012" on my Mac.
 - "OpenSSL 1.0.1g 7 Apr 2014" on windows 7
 - "OpenSSL 0.9.8y 5 Ffeb 2013" om Windows 8

**Comment by ahelsing** [comment]
Heidi reports this page has been making the sysadmin rounds: https://weakdh.org/sysadmin.html

**Comment by nbastin** [comment]
Ok, so not a complete solution (yet), but for reference, on MacOS X with Python 2.7.9 (*no* earlier version works), the following works with the requests library:

```python
import requests
import ssl
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.poolmanager import PoolManager

class TLS1HttpAdapter(HTTPAdapter):
    def init_poolmanager(self, connections, maxsize, block=False):
            self.poolmanager = PoolManager(num_pools=connections,maxsize=maxsize,block=block,ssl_version=ssl.PROTOCOL_TLSv1)

s = requests.Session()
s.mount("https://geni-scs.net.internet2.edu:8443", TLS1HttpAdapter())
s.get("https://geni-scs.net.internet2.edu:8443", cert=('portal-nbastin.pem', 'portal-nbastin.key'), verify=False)
```

You'll have to suppress an InsecureRequestWarning from urllib3, but it works fine otherwise:

```python
>>> s.get("https://geni-scs.net.internet2.edu:8443", cert=('portal-nbastin.pem', 'portal-nbastin.key'), verify=False)
Enter PEM pass phrase:
/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
<Response [404]>
```

**Comment by ahelsing** [comment]
The GMOC downgraded stunnel and OpenSSL on the SCS server to the following versions:

openssl-1.0.1e-30.el6_6.2.x86_64
stunnel-4.29-3.el6_4.x86_64

This seems to fix the immediate issue.

**Comment by ahelsing** [comment]
I wrote some code that appears to change the default protocol to TLSv1 from SSLv23, but allows switching to other protocols. This code 
 - has some debug printouts in client.py to remove
 - has only been tested on my ubu14.04 and 10.04 and Win7 systems, plus a little on my OSX Yosemite.

See https://github.com/ahelsing/geni-tools/commit/4e0ac4407dab9974a7c4e4e32eb5476216f7be5d

**Comment by ahelsing** [comment]
One approach for testing is to use `openssl s_server` as in:
`openssl s_server -verify 1 -cert ~/.gcf/am-cert.pem -key ~/.gcf/am-key.pem -msg -state -CApath ~/.gcf/trusted_roots -chain -www`

Then optionally
 - -legacy_renegotiation
 - - bugs
 - -tls1 / -ssl2 / -ssl3 / -no_ssl2 / -no_ssl3 / -no_tls1

**Comment by ahelsing** [comment]
GMOC says:
```
On Friday at 11:07:11 UTC, stunnel was updated via puppet to stunnel-4.29-3.el6_6.1.x86_64. OpenSSL was not updated at that time. Later that day OpenSSL was updated (manually) to openssl-1.0.1e-30.el6_6.4.x86_64.

This system is running CentOS 6.6.

The SCS is running directly through stunnel, so there’s no web server involved.
```

stunnel.conf:
```ini
; Debugging stuff (may be useful for troubleshooting)
;fips=no
debug = 1
output = /var/log/stunnel.log

; Certificate/key is needed in server mode and optional in client mode
cert = /etc/stunnel/stunnel.pem

; Authentication stuff needs to be configured to prevent MITM attacks
; It is not enabled by default!
verify = 2
; Don't forget to c_rehash CApath
; CApath is located inside chroot jail
;CApath = /certs
; It's often easier to use CAfile
CAfile = /etc/stunnel/ca-all.pem

; Enable support for the insecure SSLv2 protocol
;options = -NO_SSLv2
; Enable support for the insecure SSLv3 protocol
;options = -NO_SSLv3

; **************************************************************************
; * Service definitions (remove all services for inetd mode)               *
; **************************************************************************
[geni-scs]
accept  = 8443
connect = 8081

[syslog]
client = yes
accept = 10009
verify = 0
#syslog.grnoc.iu.edu
connect = 140.182.44.73:10009
```

**Comment by ahelsing** [comment]
Here's an email thread suggesting that Redhat / Centos mucked with the stunnel rpm to disable SSLv3 in the version of stunnel that I2 updated and which gave us trouble: https://www.stunnel.org/pipermail/stunnel-users/2015-January/004935.html

The poster says that forcing reverting stunnel to the version that I2 went back to is what fixed SSLv3 support for them.

Here's a site with the Centos RPMs: http://rpmfind.net/linux/RPM/centos/updates/6.6/x86_64/Packages

**Comment by ahelsing** [comment]
Here's a related post about redhat and stunnel: https://www.stunnel.org/pipermail/stunnel-users/2014-December/004903.html

**Comment by ahelsing** [comment]
I was able to reproduce the symptoms at I2 using that 'new' version of stunnel (openssl version didn't make a difference), on a CentOS 6.6 VM (thanks ExoGENI!).

By modifying the omnilib client.py to specify PROTOCOL_TLSv1 (overwriting some python library classes as described above), I can make the connection to my test server work. And connections still work from other clients and to other servers, in my testing.

While I was there, I also changed the default ciphers to the stronger list from issue #744: `HIGH:MEDIUM:!ADH:!SSLv2:!MD5:!RC4:@STRENGTH`

This code is at https://github.com/ahelsing/geni-tools/blob/tkt745-ssl/src/gcf/omnilib/xmlrpc/client.py

I have not merged this in yet, while I try to do more testing.

**Comment by ahelsing** [comment]
Luisa found an error on this system:
```
06/03 10:03:24 INFO     stitcher.py:412 Python: CPython 2.6.5
OS: Linux-2.6.32-67-generic-pae-i686-with-Ubuntu-10.04-lucid
...
06/03 10:03:24 ERROR    dossl.py:213 Call for Get credentials for slice urn:publicid:IDN+ch.geni.net:ln-test+slice+ig-chic-ig-wisc on GENI Clearinghouse SA https://ch.geni.net/SA failed.: AttributeError: SafeTransportWithCert instance has no attribute '_connection'
06/03 10:03:24 DEBUG    dossl.py:216 Traceback (most recent call last):
  File "/home/lnevers/gcf-2.9/src/gcf/omnilib/util/dossl.py", line 76, in _do_ssl
    result = fn(*args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1228, in request
    h = self.make_connection(host)
  File "/home/lnevers/gcf-2.9/src/gcf/omnilib/xmlrpc/client.py", line 56, in make_connection
    if self._connection and host_tuple == self._connection[0]:
AttributeError: SafeTransportWithCert instance has no attribute '_connection'
```

**Comment by ahelsing** [comment]
code now works on python2.6 systems, though 2.6 does not allow specifying the cipher list.

code is also copied into the gcf secure_xmlrpc_client

So Omni now uses TLSv1 and more secure ciphers where possible. Done.
